name: github_search
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^7.0.1
  flutter_svg: ^1.1.1+1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  pretty_dio_logger: ^1.2.0-beta-1
  rxdart: ^0.27.7
  url_launcher: ^6.1.7

dev_dependencies:
  analyzer: ^4.3.0
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  copy_with_extension_gen: ^4.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  hive_generator: ^1.1.3
  json_serializable: ^6.3.1
  lint: ^1.8.2
  mocktail: ^0.3.0

flutter:
  assets:
    - assets/png_images/
    - secrets/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
  uses-material-design: true

flutter_intl:
  enabled: true